### PR TITLE
Add clipboard copy module

### PR DESCRIPTION
**Pull request by KevinBatdorf**
Wanted to write some Vue code and saw someone request this on twitter so I figured why not. Let me know if I missed something!

https://user-images.githubusercontent.com/1478421/105005995-9fdb9a80-5a68-11eb-9e8f-41d691e0e3f5.mp4

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
i think i need to add some keyboard focus styles so the button shows when the user is tabbing around. will look at that a bit later.

**Comment by jbrooksuk** [comment]
Thanks @KevinBatdorf! I've made some adjustments so that we're using Tailwind group and focus states. I've also fixed alignment of the icon and simplified the command we copy so no RegEx is used.

**Comment by KevinBatdorf** [comment]
@jbrooksuk  Ah right. `name` works better. You could probably simplify further by just accessing the prop directly too. `textarea.textContent = this.command.name`

For the group, I think you need to add a variant to get the `group-hover` working with opacity. That's why I went with css.

**Comment by jbrooksuk** [comment]
I had to add the TailwindCSS v2 compatibility modules.

**Pull request merged**
