### PR TITLE
Added dark mode

### PR DESCRIPTION
**Pull request by ash-jc-allen**
Hey James! 😄

This PR adds a dark mode to the site. I'm by no means a designer so you might not be happy with the changes I've made, but hopefully, it can at least provide a good starting point. I've also not got too much experience with Nuxt so there's a possibility that some of the stuff I've done can be done much better.

I also couldn't get `npm run dev` to run because I kept getting this error:

```
Error: Cannot find module 'tailwindcss/defaultTheme'
```

Running `npm install tailwindcss` seemed to fix it. I don't know if this was an issue with the repo or just something on my end that I wasn't doing right? But if it needs removing again from the `package.json`, I'll make sure to revert that back.

I've attached some images to give you a comparison of the light and dark modes. Hopefully, you're happy with the general approach. If this is something that you might consider merging but you want some changes making first, let me know and I'll do them ASAP :)

darkmode
lightmode

### CODE REVIEW

**Comment by jbrooksuk** [comment]
This is awesome, thank you @ash-jc-allen 👏🏻 

One thing I've noticed is that by default, the design will change with the OS system setting of light/dark mode. However, once toggled, there is no way to follow the system setting again. Maybe we need a dropdown? Light / Dark / System.

**Comment by ash-jc-allen** [comment]
I knew I'd probably missed something off haha!

But yeah sure, I can get that switched out for a dropdown instead. Is there any design in particular you might want me to use? Or do you want me to use a standard dropdown like what's used for toggling the Laravel versions? :)

**Comment by jbrooksuk** [comment]
I'd just go with a `select` for now :)

**Comment by ash-jc-allen** [comment]
Sweet! I've updated it now to use a `select` instead.

I also added in emojis for each option because I thought they looked pretty cool. And it also matches the same style as your 'back to top' button. But, of course, if you'd prefer it without, I can take them out 😄

Screenshot 2021-12-24 at 00 47 20
Screenshot 2021-12-24 at 00 47 26
Screenshot 2021-12-24 at 00 48 54

**Comment by jbrooksuk** [comment]
This is perfect! 

Thank you! Happy holidays!

**Comment by ash-jc-allen** [comment]
Sweet! And thanks, you too! 😄

**Pull request merged**
