### PR TITLE
Add server api endpoint

### LINKED ISSUE #25: Add api endpoints
Have you though about adding api endpoints that show available commands and descriptions?

I think if you upgrade to nuxt 3 it's built in (maybe even in nuxt 2, I just don't know).

https://v3.nuxtjs.org/guide/features/server-routes

It could then be consumed by something like Alfred or Raycast. I wrote a [Forge Raycast extension](https://www.raycast.com/KevinBatdorf/laravel-forge) and was thinking to show available artisan commands by Laravel version that can execute via the [site command](https://forge.laravel.com/api-documentation#execute-command) endpoint. 

I thought about getting the commands from the server like the build command here does, but that might be too intrusive, while an API would be perfect (or I do both and have the former be opt in).

### PR DESCRIPTION
**Pull request by KevinBatdorf**
Hey James, this PR adds an api endpoint to query the docs. I also upgraded Nuxt 2 to Nuxt bridge, which essentially adds v3 features to v2.

Files changed followed the migration guide here: https://v3.nuxtjs.org/bridge/overview

I've only tested this locally so far so there could be further cors setup required.

List all commands:
```
GET /api
```
Search for a command:
```
GET /api?s=database
```
Specify a version:
```
GET /api?v=8.x
```

closes #25

### CODE REVIEW

**Comment by jbrooksuk** [comment]
This is awesome @KevinBatdorf!

Can we keep the `generate` script please. Saves changing the Vercel configuration.

**Comment by KevinBatdorf** [comment]
Oh right. I think `nuxt build` and `nuxt generate` are the same now but I'll add the alias.

**Comment by KevinBatdorf** [comment]
Vercel is still failing to deploy it. I wonder if it's a change in nuxt 3. I can try setting it up on my own account later or tomorrow. I'll follow up.

**Comment by KevinBatdorf** [comment]
I can't get it to build on Vercel unfortunately. Tried everything I could think of, but nothing got it to build. The error isn't super helpful either, just that it failed generating the page routes. it could be anything, I guess. It generates fine locally for me though.

```
[error] [worker reload] [worker] exited
--
23:11:31.672 | at Worker.<anonymous> (node_modules/nitropack/dist/chunks/prerender.mjs:2039:14)
23:11:31.672 | at Object.onceWrapper (node:events:640:26)
23:11:31.673 | at Worker.emit (node:events:520:28)
23:11:31.673 | at Worker.emit (node:domain:475:12)
23:11:31.673 | at Worker.[kOnExit] (node:internal/worker:278:10)
23:11:31.673 | at Worker.<computed>.onexit (node:internal/worker:198:20)
23:11:31.737 | [error] Error generating route "/":
23:11:31.741 | [error] Error generating route "/9.x/":
23:11:31.742 | [error] Error generating route "/8.x/":
23:11:31.742 | [error] Error generating route "/7.x/":
23:11:31.742 | [error] Error generating route "/6.x/":
```

The API route works: https://artisan-page-5pljqa5ue-alt-three.vercel.app/api

If you have any ideas let me know. otherwise maybe just hold off a bit and try again on a future nuxt version update.

**Comment by KevinBatdorf** [comment]
If we can't get it working, would you be willing to host the API independently of this app? For example, you can set up a blank repo `api.artisan.page`, then I'll PR it with a basic next.js app that runs the same workflows on a schedule, but has no frontend. Only the workflow and a single endpoint. Then you host it at api.artisan.page on Vercel. 

I want to use the API for an app to [execute commands via the forge API](https://forge.laravel.com/api-documentation#site-commands), and just feel like having it here would just increase the credibility (for obvious reasons). Otherwise I could set it up on my own. I understand if not though.

**Comment by KevinBatdorf** [comment]
I ported it here in case you are interested! Let me know and I can transfer the app or whatever.

https://github.com/KevinBatdorf/laravel-docs-api

**Comment by jbrooksuk** [comment]
@KevinBatdorf why don't we just update Nuxt.js?

**Comment by KevinBatdorf** [comment]
We'd have to just rebuild the entire frontend too (using Vue 3) and I'm just much more experienced with React than Vue3.

If you wanted to start on it though I'd happily contribute, but I'm not sure it's worth the time to rebuild the current site anyway since it works fine now.

**Pull request closed without merging**
