### PR TITLE
Add version routing

### PR DESCRIPTION
**Pull request by KevinBatdorf**
This adds the routing part only. Hash links should work on both versions.

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
Hmm didn't seem to deploy. I'll push this to my master branch so it will deploy on my account

**Comment by KevinBatdorf** [comment]
That seems to have deployed fine. I'll hold off on the other stuff until you have time to look at this one.

**Comment by jbrooksuk** [comment]
It works!

One thing I noticed is that if you're searching for something and then switch version, the results aren't automatically filtered down.

**Comment by KevinBatdorf** [comment]
Will update this tomorrow, and one of the next PRs too!

**Comment by KevinBatdorf** [comment]
it ended up being easier to add the search param to the query string than imperatively checking for it everywhere. You can see the update here:

https://artisan-page.kevinbatdorf.vercel.app/?search=db

Not really sure how I feel about it yet but take a look and tell me what you think?

**Comment by KevinBatdorf** [comment]
I merged in the master branch but wasn't sure how to run styleCI to fix the code styles (i'm used to prettier). If you need me to do something let me know. Also, I have time tomorrow if you have any thoughts or other ideas! (no rush though, of course)

**Comment by jbrooksuk** [comment]
@KevinBatdorf sorry for the delay in this.

I'm still not sure on the `?search=` being there by default. And, if you have an existing bookmark, http://localhost:3000/#down it no longer works.

**Comment by jbrooksuk** [comment]
This is now live, for example https://artisan.page/laravel/6.x#env

**Pull request closed without merging**
