### PR TITLE
Feature/automate build process

### PR DESCRIPTION
**Pull request by KevinBatdorf**
Hey, so this this works pretty well but some things to note:

- The GH action workflow will re-commit changes after it generates the commands list. This sometimes (well, many times) creates a race condition situation. I added a retry but maybe you have a better approach. Might also be good enough as-is though, as you can just re-run the job if needed and it should work. ie. It won't break anything.

- The packages and versions are updated in the manifest file. 

- I left the styling for you but added some sensible defaults. 

- The packages don't install on anything below 8.x as it would require some logic to reconcile the version numbers. Composer throws dependency requirement error, but it won't crash the workflow. Probably not worth adding support?

Feel free to take ever the PR of course, but if there's anything you want me to tweak let me know. And of course if you hate it, no need to merge it ha ha. It seems like a lot of work but I took it on to practice a complex GH action workflow, so it time well spent regardless!

https://user-images.githubusercontent.com/1478421/105506846-1264a880-5cfd-11eb-87f8-2bcb3fb18d4b.mp4

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
I think you have to enable GH Actions for it to run, although this PR already has the compiled code so the preview Vercel deployed is up to date.

**Comment by KevinBatdorf** [comment]
The clipboard group styling doesn't seem to be working here. Not sure where I messed that up (it's showing locally). Also not sure what added that yarn lock file either. Maybe related

**Comment by jbrooksuk** [comment]
Just a quick thought, versions and packages aren't currently linkable. I think that we could use the Router for this?

**Comment by KevinBatdorf** [comment]
Looks like none of the links work actually. I guess because the content isn't loaded right away. Maybe load in the latest Laravel data by default? I'll try that out now.

**Comment by KevinBatdorf** [comment]
So now I added back the previous functionality. So it would link to the command via a #hash value, but only on the latest Laravel version (currently v8.x). 

A router would be good if you want to be able to link to various versions as well. Probably better in another PR though?

How would the routes look? Maybe like this?
atrisan.page/8.x/authclear-resets

The build is failing now so I'll look into that

**Comment by KevinBatdorf** [comment]
The build is failing but looks like it deployed properly. First time using Vercel so not sure what happened. Maybe because I removed the two lock files

https://artisan-page-6w1o6xwqn.vercel.app/#scoutflush

**Comment by jbrooksuk** [comment]
Thanks @KevinBatdorf! I'll have a good read through this later and give some proper feedback then :)

**Comment by jbrooksuk** [comment]
@KevinBatdorf thanks again for this! Here is my feedback as I've tested it:

- I think that by default the `/` route should always point to the latest version.
- When selecting a version, I think it should be its own route `/7.x`, `/6.x` etc. This allows us to deep link to a particular version.
- I'm not sure I'm keen on the idea of all packages being loaded in by default, it makes the reference **a lot** longer and could be optionally toggled on. Perhaps we could add a query string that loads `?packages=scout,breeze` or do you feel that's too much?

Perhaps we should break this feature down into multiple PRs:

1. Routing (using manually generated JSON files).
2. Additional packages.
3. Automated build processes.

**Comment by KevinBatdorf** [comment]
Yeah that makes sense. I'll break it down into those pieces. 

Using a query string for packages might not be too useful, though. I don't think users will need to narrow down what they are looking for by including multiple packages. I imagine they will only either want core commands, or a way to select a package. What do you think? You probably know better than I do.

What about if there is a "core" button (the default state if no hash links) that only shows the core items, but leaves the search field blank?
Screen Shot 2021-01-26 at 2 15 36 PM

That keeps the logic all together and makes it easy to have a search term search everything.

It might be better to remove the #​hash linking too, and use a query param like https://github.com/jbrooksuk/artisan.page/pull/11, that way the item they are looking for is always filtered and at the top

**Comment by jbrooksuk** [comment]
Perhaps "default" instead of "core"? I dunno...

Also, we absolutely need to keep the hash linking so that we don't break backwards compatibility with current bookmarks.

**Comment by KevinBatdorf** [comment]
I can put "default" and it can be changed easily enough later.

Im thinking to support the hash links but deprecate them, so to speak. So the hash link will work forever if used, but new users will get the query param. Essentially the hash will be converted to the query param immediately.

The issue is that if some commands (from packages) are going to be hidden in the default state, there need to be a bit more complexity to the filtering logic on page load. Where as the simple approach would be to just populate the query string. The added benefit is the user can link to their specific search params (another feature could be multiple searches, perhaps like ?query=sail|scout|make)

So if you type `example.com#my-command` it will immediately convert to `example.com?query=my-command

Let me know what you think. I can try it out anyway so you can see it, then we can adjust after if it's no good.

I'm flying Thailand to USA today though so probably won't make any progress until over the weekend. 26 hours of travel so I might be a bit jet-lagged ha ha.

**Comment by jbrooksuk** [comment]
@KevinBatdorf you know, I think it's fine as it is.

I still think we need to address each version being under its own page, but have `/#down` always point to the latest version, but you could do `/8.x#down` too. Does this make sense?

**Comment by jbrooksuk** [comment]
Here's my thinking:

- When landing on `/` we should load the latest version of Laravel.
- When changing version via the dropdown, we should redirect to `/7.x` or whichever version is then selected. If `8.x` is the latest version, then `/` will load the same contents as `8.x`

**Comment by KevinBatdorf** [comment]
These PRs are a bit out of sync and not sure I can easily pick up where i left off and remember what I was doing 😎

I can make a new smaller PR if you want to make a specific feature list or something? 

I think maybe the most valuable change would be [the GH action](https://github.com/jbrooksuk/artisan.page/blob/7fa2bb2b24bfc15b55191d886b90ae6226b35e71/.github/workflows/build-command-file.yml) that should future proof this (maybe it could even be expanded to detect versions automatically too).

OR.. what else are you working on? I'm so deep into React right now that looking at Vue code is tripping me up too.

**Comment by jbrooksuk** [comment]
Thanks @KevinBatdorf! I've moved this work into `master` and have taken packages out of this for now. I'll probably work on adding packages later :)

**Pull request closed without merging**
